### ISSUE TITLE
Invalid time zone name when running the app in Android simulator

### ISSUE THREAD

**Issue by cjmao** [itsandytran/Litespeed#13]
Below is a screenshot of the error when launching the app in Android simulator:

<img width="398" alt="image" src="https://github.com/user-attachments/assets/ad346fbe-03d8-488f-bfb7-cc50db5c7748">

**Comment by itsandytran** [comment]
Thanks, will look into this today.

**Comment by cjmao** [comment]
It's not a high priority issue I think. Can fix it later, though it might only take a few minutes to fix it.
